// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJeE2bd_Y3l1Q19jsWrnYwttZ_SHHssaA',
    appId: '1:727616627428:web:14baff98c708c825c342f1',
    messagingSenderId: '727616627428',
    projectId: 'mustafa-dairy',
    authDomain: 'mustafa-dairy.firebaseapp.com',
    storageBucket: 'mustafa-dairy.appspot.com',
    measurementId: 'G-LKS0K02MLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq7pOOLy2oiZsoDKikzqLNvbcc8fddk1g',
    appId: '1:727616627428:android:8f3c88a96de85ddac342f1',
    messagingSenderId: '727616627428',
    projectId: 'mustafa-dairy',
    storageBucket: 'mustafa-dairy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC29-IZyBvpSS-8TSW17DJUiXss723GBDQ',
    appId: '1:727616627428:ios:8708b56d90384b95c342f1',
    messagingSenderId: '727616627428',
    projectId: 'mustafa-dairy',
    storageBucket: 'mustafa-dairy.appspot.com',
    iosBundleId: 'com.example.mustafaDairy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC29-IZyBvpSS-8TSW17DJUiXss723GBDQ',
    appId: '1:727616627428:ios:a4280c46a23844f7c342f1',
    messagingSenderId: '727616627428',
    projectId: 'mustafa-dairy',
    storageBucket: 'mustafa-dairy.appspot.com',
    iosBundleId: 'com.example.mustafaDairy.RunnerTests',
  );
}
